name: auto create unsafelist.txt
on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  job_create_file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python main.py
